
services:
  mysql:
    image: mysql:8.0
    container_name: spotify_client
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: renaido #ahsdasgbdhjasbdjyh
      MYSQL_DATABASE: spotify_client
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network
volumes:
  mysql_data:
  app_logs:

networks:
  mysql_network:
    driver: bridge
